<?php

namespace Proxies\__CG__\MAT\SitioBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Posicion extends \MAT\SitioBundle\Entity\Posicion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posNoticia', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posNoticiainterna', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posDestacado', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posVideo', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posEstadistica', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posEnlace', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'id', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idNoticia', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idNoticiainterna', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idDestacado', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idVideo', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idEstadistica', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idEnlace');
        }

        return array('__isInitialized__', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posNoticia', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posNoticiainterna', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posDestacado', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posVideo', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posEstadistica', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'posEnlace', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'id', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idNoticia', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idNoticiainterna', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idDestacado', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idVideo', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idEstadistica', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Posicion' . "\0" . 'idEnlace');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Posicion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPosNoticia($posNoticia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosNoticia', array($posNoticia));

        return parent::setPosNoticia($posNoticia);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosNoticia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosNoticia', array());

        return parent::getPosNoticia();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosNoticiainterna($posNoticiainterna)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosNoticiainterna', array($posNoticiainterna));

        return parent::setPosNoticiainterna($posNoticiainterna);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosNoticiainterna()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosNoticiainterna', array());

        return parent::getPosNoticiainterna();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosDestacado($posDestacado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosDestacado', array($posDestacado));

        return parent::setPosDestacado($posDestacado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosDestacado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosDestacado', array());

        return parent::getPosDestacado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosVideo($posVideo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosVideo', array($posVideo));

        return parent::setPosVideo($posVideo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosVideo', array());

        return parent::getPosVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosEstadistica($posEstadistica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosEstadistica', array($posEstadistica));

        return parent::setPosEstadistica($posEstadistica);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosEstadistica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosEstadistica', array());

        return parent::getPosEstadistica();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosEnlace($posEnlace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosEnlace', array($posEnlace));

        return parent::setPosEnlace($posEnlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosEnlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosEnlace', array());

        return parent::getPosEnlace();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdNoticia(\MAT\SitioBundle\Entity\Noticia $idNoticia = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdNoticia', array($idNoticia));

        return parent::setIdNoticia($idNoticia);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdNoticia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdNoticia', array());

        return parent::getIdNoticia();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdNoticianterna(\MAT\SitioBundle\Entity\NoticiaInterna $idNoticiaInterna = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdNoticianterna', array($idNoticiaInterna));

        return parent::setIdNoticianterna($idNoticiaInterna);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdNoticiainterna()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdNoticiainterna', array());

        return parent::getIdNoticiainterna();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDestacado(\MAT\SitioBundle\Entity\Destacado $idDestacado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDestacado', array($idDestacado));

        return parent::setIdDestacado($idDestacado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDestacado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDestacado', array());

        return parent::getIdDestacado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdVideo(\MAT\SitioBundle\Entity\Video $idVideo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdVideo', array($idVideo));

        return parent::setIdVideo($idVideo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVideo', array());

        return parent::getIdVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEstadistica(\MAT\SitioBundle\Entity\Estadistica $idEstadistica = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEstadistica', array($idEstadistica));

        return parent::setIdEstadistica($idEstadistica);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEstadistica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEstadistica', array());

        return parent::getIdEstadistica();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEnlace(\MAT\SitioBundle\Entity\Enlace $idEnlace = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEnlace', array($idEnlace));

        return parent::setIdEnlace($idEnlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEnlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEnlace', array());

        return parent::getIdEnlace();
    }

}
