<?php

namespace Proxies\__CG__\MAT\SitioBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Banner extends \MAT\SitioBundle\Entity\Banner implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'rutaBanner', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'rutaFooter', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'rutaLogo', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'rutaSplash', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'fechaHora', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'visibleSplash', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'id', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'idUsuario');
        }

        return array('__isInitialized__', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'rutaBanner', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'rutaFooter', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'rutaLogo', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'rutaSplash', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'fechaHora', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'visibleSplash', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'id', '' . "\0" . 'MAT\\SitioBundle\\Entity\\Banner' . "\0" . 'idUsuario');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Banner $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setRutaBanner($rutaBanner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRutaBanner', array($rutaBanner));

        return parent::setRutaBanner($rutaBanner);
    }

    /**
     * {@inheritDoc}
     */
    public function getRutaBanner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRutaBanner', array());

        return parent::getRutaBanner();
    }

    /**
     * {@inheritDoc}
     */
    public function setRutaFooter($rutaFooter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRutaFooter', array($rutaFooter));

        return parent::setRutaFooter($rutaFooter);
    }

    /**
     * {@inheritDoc}
     */
    public function getRutaFooter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRutaFooter', array());

        return parent::getRutaFooter();
    }

    /**
     * {@inheritDoc}
     */
    public function setRutaLogo($rutaLogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRutaLogo', array($rutaLogo));

        return parent::setRutaLogo($rutaLogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getRutaLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRutaLogo', array());

        return parent::getRutaLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRutaSplash($rutaSplash)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRutaSplash', array($rutaSplash));

        return parent::setRutaSplash($rutaSplash);
    }

    /**
     * {@inheritDoc}
     */
    public function getRutaSplash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRutaSplash', array());

        return parent::getRutaSplash();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaHora($fechaHora)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaHora', array($fechaHora));

        return parent::setFechaHora($fechaHora);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaHora()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaHora', array());

        return parent::getFechaHora();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisibleSplash($visibleSplash)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisibleSplash', array($visibleSplash));

        return parent::setVisibleSplash($visibleSplash);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisibleSplash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisibleSplash', array());

        return parent::getVisibleSplash();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(\MAT\SitioBundle\Entity\Usuario $idUsuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

}
